import {test,expect,type Page} from '@playwright/test';
async function enter(page:Page){
 await page.goto('/');await expect(page.locator('main')).toHaveAttribute('data-ready','true',{timeout:30000});await page.waitForTimeout(2300);await page.screenshot({path:'tmp/qa/01-intro.png'});await page.mouse.wheel(0,250);await expect(page.locator('main')).toHaveAttribute('data-scene','narrative');await page.waitForTimeout(1000);
 for(let i=0;i<95;i++){await page.mouse.wheel(0,240);await page.waitForTimeout(60);if(await page.locator('main').getAttribute('data-scene')==='categories')break}
 await expect(page.locator('main')).toHaveAttribute('data-scene','categories');await page.waitForTimeout(1100);
 for(let i=0;i<7;i++){await page.mouse.wheel(0,240);await page.waitForTimeout(180)}await expect(page.locator('main')).toHaveAttribute('data-scene','arrival');await page.waitForTimeout(2200);await page.mouse.wheel(0,250);await expect(page.locator('main')).toHaveAttribute('data-scene','explorer');await page.waitForTimeout(2200);
}
test('full material experience and visual layouts',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await enter(page);await page.screenshot({path:'tmp/qa/05-explorer.png'});await expect(page.locator('[data-label]')).toHaveCount(8);
 for(const size of [{width:1280,height:800},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(size);await page.waitForTimeout(800);const boxes=await page.locator('[data-label]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}));for(const b of boxes){expect(b.x).toBeGreaterThanOrEqual(0);expect(b.y).toBeGreaterThanOrEqual(0);expect(b.x+b.w).toBeLessThanOrEqual(size.width);expect(b.y+b.h).toBeLessThanOrEqual(size.height)}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y,`labels ${i}/${j}`).toBeFalsy()}await page.screenshot({path:`tmp/qa/explorer-${size.width}.png`})}
 await page.setViewportSize({width:1280,height:800});await page.locator('[data-label="shell-composite"]').click({force:true});await expect(page.locator('main')).toHaveAttribute('data-scene','detail');await page.waitForTimeout(4000);await page.screenshot({path:'tmp/qa/06-detail.png'});await expect(page.getByRole('slider',{name:'Material zoom'})).toHaveAttribute('aria-valuenow','100');await page.getByRole('button',{name:'Add to favorites',exact:true}).click({force:true});await expect(page.locator('main')).toHaveAttribute('data-favorites','1');
 const slider=page.getByRole('slider',{name:'Material zoom'});await slider.focus();await page.keyboard.press('End');await expect(slider).toHaveAttribute('aria-valuenow','300');await page.waitForTimeout(600);await page.screenshot({path:'tmp/qa/06-micro.png'});await page.keyboard.press('Home');await expect(slider).toHaveAttribute('aria-valuenow','40');await page.mouse.move(700,500);await page.mouse.wheel(0,-460);await expect(slider).toHaveAttribute('aria-valuenow','100');
 await page.getByRole('button',{name:'DEFORM',exact:true}).click({force:true});await expect(page.locator('main')).toHaveAttribute('data-mode','deform');await page.mouse.move(600,400);await page.mouse.down();await page.mouse.move(660,430,{steps:8});await page.screenshot({path:'tmp/qa/06-deform.png'});await page.mouse.up();await page.getByRole('button',{name:'OBSERVE',exact:true}).click({force:true});await page.mouse.move(600,400);await page.mouse.down();await page.mouse.move(900,550,{steps:15});await page.mouse.up();await page.waitForTimeout(1000);await page.screenshot({path:'tmp/qa/06-3d.png'});
 await page.getByRole('button',{name:'Open favorites'}).click({force:true});await page.waitForTimeout(2000);await expect(page.locator('main')).toHaveAttribute('data-scene','favorites');await expect(page.locator('[data-label]')).toHaveCount(1);await page.screenshot({path:'tmp/qa/07-favorites-one.png'});await page.locator('[data-label="shell-composite"]').click({force:true});await page.waitForTimeout(1100);await page.getByRole('button',{name:'Remove from favorites'}).click({force:true});await page.getByRole('button',{name:'Return to previous scene'}).click({force:true});await page.waitForTimeout(1100);await expect(page.locator('main')).toHaveAttribute('data-scene','favorites');await expect(page.locator('[data-label]')).toHaveCount(0);await expect(page.locator('.material-info')).toHaveCount(0);await page.screenshot({path:'tmp/qa/07-empty.png'});await page.getByRole('button',{name:'Return to previous scene'}).click({force:true});await page.waitForTimeout(1100);await expect(page.locator('main')).toHaveAttribute('data-scene','detail');await expect(page.locator('main')).toHaveAttribute('data-active-id','shell-composite');await page.getByRole('button',{name:'Return to previous scene'}).click({force:true});await page.waitForTimeout(1100);await expect(page.locator('main')).toHaveAttribute('data-scene','explorer');
 const ids=await page.locator('[data-label]').evaluateAll(es=>es.map(e=>e.getAttribute('data-label')!));for(const id of ids){await page.locator(`[data-label="${id}"]`).click({force:true});await page.waitForTimeout(1100);await page.getByRole('button',{name:'Add to favorites',exact:true}).click({force:true});await page.getByRole('button',{name:'Return to previous scene'}).click({force:true});await page.waitForTimeout(1100)}await expect(page.locator('main')).toHaveAttribute('data-favorites','8');await page.getByRole('button',{name:'Open favorites'}).click({force:true});await page.waitForTimeout(3500);await page.screenshot({path:'tmp/qa/07-eight.png'});const before=await page.locator('main').getAttribute('data-active-id');await page.mouse.wheel(0,250);await expect(page.locator('main')).toHaveAttribute('data-info','false');await expect(page.locator('.more a')).toHaveCount(0);await page.waitForTimeout(1800);await expect(page.locator('main')).toHaveAttribute('data-info','false');await page.waitForTimeout(3500);await expect(page.locator('main')).toHaveAttribute('data-info','true');expect(await page.locator('main').getAttribute('data-active-id')).not.toBe(before);await page.getByRole('button',{name:'Mute sound'}).click({force:true});await expect(page.getByRole('button',{name:'Enable sound'})).toBeVisible();
 await page.reload();await expect(page.locator('main')).toHaveAttribute('data-favorites','0');expect(errors).toEqual([]);
});
test('timing, gesture isolation, iron state, audio and reduced motion',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await enter(page);
 const ids=await page.locator('[data-label]').evaluateAll(es=>es.map(e=>e.getAttribute('data-label')!));
 for(const id of ids){await page.locator(`[data-label="${id}"]`).click({force:true});await page.waitForTimeout(1000);await page.getByRole('button',{name:'DEFORM',exact:true}).click({force:true});await page.mouse.move(550,450);await page.mouse.down();await page.mouse.move(595,470,{steps:5});await page.waitForTimeout(180);const deformation=await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.deformation});expect(deformation,`${id} deform`).toBeGreaterThan(.05);await page.mouse.up();await page.waitForTimeout(800);expect(await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.deformation})).toBeLessThan(.08);await page.getByRole('button',{name:'Return to previous scene'}).click({force:true});await page.waitForTimeout(1000)}
 await page.locator('[data-label="magnetic-iron"]').click({force:true});await page.waitForTimeout(1100);await page.getByRole('button',{name:'DEFORM',exact:true}).click({force:true});await page.mouse.click(550,450);await expect(page.locator('main')).toHaveAttribute('data-solid','true');await page.mouse.down();await page.mouse.move(590,450,{steps:3});await page.waitForTimeout(250);expect(await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.deformation})).toBeLessThan(.1);await page.waitForTimeout(2100);await expect(page.locator('main')).toHaveAttribute('data-solid','false');await page.waitForTimeout(200);expect(await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.deformation})).toBeGreaterThan(.2);await page.mouse.up();
 await page.getByRole('button',{name:'OBSERVE',exact:true}).click({force:true});await page.mouse.click(550,450);await expect(page.locator('main')).toHaveAttribute('data-solid','false');await page.mouse.move(550,450);await page.mouse.down();await page.mouse.move(850,520,{steps:12});await page.mouse.up();const q=await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.view.rotation});expect(Math.abs(q[0])+Math.abs(q[1])).toBeGreaterThan(.1);
 await page.getByRole('button',{name:'Mute sound'}).click({force:true});await page.waitForTimeout(350);const muted=await page.evaluate(async()=>{const {audio}=await import('/src/audio.ts');const a=new Float32Array(512);audio.analyser?.getFloatTimeDomainData(a);return {volume:audio.volume,gain:audio.master?.gain.value,peak:Math.max(...a.map(Math.abs)),loop:!!audio.loop}});expect(muted.volume).toBe(.13);expect(muted.gain).toBeLessThan(.001);expect(muted.peak).toBeLessThan(.001);expect(muted.loop).toBe(false);
 await page.getByRole('button',{name:'Enable sound'}).click({force:true});await page.waitForTimeout(350);expect(await page.evaluate(async()=>{const {audio}=await import('/src/audio.ts');return audio.master?.gain.value})).toBeCloseTo(.13,2);
 const slider=page.getByRole('slider',{name:'Material zoom'});const box=(await slider.boundingBox())!;await page.mouse.move(box.x+4,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+60,box.y-100,{steps:4});await page.mouse.up();await expect(slider).toHaveAttribute('aria-valuenow','300');expect(await page.evaluate(async()=>{const m=await import('/src/state.ts');return m.runtime.gesture})).toBe(false);
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await expect(page.locator('main')).toHaveAttribute('data-ready','true');expect(await page.locator('.ambient-light').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');expect(errors).toEqual([]);
});
test('narrative comma gates stop until new input',async({page})=>{
 await page.goto('/');await expect(page.locator('main')).toHaveAttribute('data-ready','true');await page.waitForTimeout(1000);await page.mouse.wheel(0,240);await page.waitForTimeout(1000);for(let i=0;i<7;i++){await page.mouse.wheel(0,240);await page.waitForTimeout(60)}await page.waitForTimeout(100);let before=await page.locator('.narrative p').innerText();await page.waitForTimeout(1600);expect(await page.locator('.narrative p').innerText()).toBe(before);
 for(let i=0;i<8;i++){await page.mouse.wheel(0,240);await page.waitForTimeout(50);before=await page.locator('.narrative p').innerText();if(before.endsWith(','))break}expect(before.endsWith(',')).toBeTruthy();await page.mouse.wheel(0,240);expect(await page.locator('.narrative p').innerText()).toBe(before);await page.waitForTimeout(1600);expect(await page.locator('.narrative p').innerText()).toBe(before);await page.mouse.wheel(0,240);await expect(page.locator('.narrative p')).not.toHaveText(before);
});

