const presets:Record<string,[number,number,number]>={plate:[1650,.1,.3],foam:[180,.45,.12],paper:[2600,.16,.15],fiber:[1800,.35,.18],leather:[320,.5,.16],iron:[3800,.2,.24],membrane:[650,.6,.12],cushion:[800,.45,.2]};
const cues=['assemble','dissolve','reform','category-expand','category-return','arrival','detail-enter','detail-return','favorites-enter','favorites-return','favorites-step','favorite-on','favorite-off','typing'];
export class AudioManager {
 context?:AudioContext;master?:GainNode;analyser?:AnalyserNode;bus?:GainNode;ambient?:GainNode;enabled=true;volume=.13;voices=0;loop?:{source:AudioBufferSourceNode;gain:GainNode};buffer?:AudioBuffer;
 async unlock(){if(this.context){if(this.context.state==='suspended')await this.context.resume();return}const c=this.context=new AudioContext();this.bus=c.createGain();const limiter=c.createDynamicsCompressor();limiter.threshold.value=-14;limiter.ratio.value=12;this.master=c.createGain();this.master.gain.value=this.enabled?this.volume:0;this.analyser=c.createAnalyser();this.analyser.fftSize=512;this.bus.connect(limiter).connect(this.master).connect(this.analyser).connect(c.destination);this.buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate);const a=this.buffer.getChannelData(0);let v=0;for(let i=0;i<a.length;i++){v=(v+Math.random()*.2-.1)*.97;a[i]=v}this.ambient=c.createGain();this.ambient.gain.value=.024;for(const hz of [54,80.1,108.3]){const o=c.createOscillator();o.type='sine';o.frequency.value=hz;o.connect(this.ambient);o.start()}this.ambient.connect(this.bus);}
 set(enabled:boolean,volume=this.volume){this.enabled=enabled;this.volume=volume;if(this.master&&this.context)this.master.gain.setTargetAtTime(enabled?volume:0,this.context.currentTime,.025)}
 cue(id:string,kind='leather') {const c=this.context;if(!c||!this.bus||!this.buffer||c.state!=='running'||this.voices>=10)return;this.voices++;const index=Math.max(0,cues.indexOf(id));const p=presets[kind]||presets.leather;const source=c.createBufferSource();source.buffer=this.buffer;source.playbackRate.value=.65+index*.09;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=id==='typing'?1100:(p[0]*(.55+index*.055));filter.Q.value=.5;const gain=c.createGain();const duration=id==='typing'?.025:.14+(index%4)*.045;gain.gain.setValueAtTime(0,c.currentTime);gain.gain.linearRampToValueAtTime(id==='typing'?.018:p[2],c.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);source.connect(filter).connect(gain).connect(this.bus);source.start();source.stop(c.currentTime+duration+.03);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();this.voices--};}
 start(kind:string,gesture:string){this.stop();const c=this.context;if(!c||!this.bus||!this.buffer)return;this.cue(gesture==='rotate'?'detail-enter':'arrival',kind);const p=presets[kind];const source=c.createBufferSource();source.buffer=this.buffer;source.loop=true;source.playbackRate.value=gesture==='zoom'?.6:1;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=p[0];filter.Q.value=p[1];const gain=c.createGain();gain.gain.setValueAtTime(0,c.currentTime);gain.gain.linearRampToValueAtTime(p[2]*.5,c.currentTime+.12);source.connect(filter).connect(gain).connect(this.bus);source.start();this.loop={source,gain};this.ambient?.gain.setTargetAtTime(.01,c.currentTime,.1)}
 stop(){const c=this.context;if(!c)return;if(this.loop){const {source,gain}=this.loop;gain.gain.setTargetAtTime(0,c.currentTime,.04);source.stop(c.currentTime+.2);source.onended=()=>source.disconnect();this.loop=undefined}this.ambient?.gain.setTargetAtTime(.024,c.currentTime,.2)}
 suspend(){this.stop();void this.context?.suspend()}
}
export const audio=new AudioManager();
