import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {audio} from './audio';
import {runtime,smooth,type Scene} from './state';
import {shapeIds} from './data/materials';
export function Type({text,delay=1250,instant=false,className='',style}:{text:string;delay?:number;instant?:boolean;className?:string;style?:CSSProperties}){
 const [count,setCount]=useState(instant?text.length:0);
 useEffect(()=>{if(instant){setCount(text.length);return}setCount(0);let frame=0,last=0;const start=performance.now()+delay;const tick=(now:number)=>{const n=Math.min(text.length,Math.max(0,Math.floor((now-start)/25)));if(n!==last){setCount(n);if(Math.floor(n/3)!==Math.floor(last/3))audio.cue('typing');last=n}if(n<text.length)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[text,delay,instant]);
 return <span className={`typed ${className}`} style={style} aria-label={text}><span aria-hidden="true" className="type-space">{text}</span><span aria-hidden="true" className="type-ink">{text.slice(0,count)}</span></span>
}
export function Outline({name,text,instant=false,delay=1250,className=''}:{name:string;text:string;instant?:boolean;delay?:number;className?:string}){
 const [count,setCount]=useState(instant?text.length:0);useEffect(()=>{setCount(instant?text.length:0);if(instant)return;let frame=0;const start=performance.now()+delay;const tick=(now:number)=>{const n=Math.min(text.length,Math.max(0,Math.floor((now-start)/45)));setCount(n);if(n<text.length)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[name,text,instant,delay]);
 return <span className={`outline ${className}`} role="img" aria-label={text}><img src={`/assets/branding/${name}_outline_v01.svg`} alt="" style={{clipPath:`inset(0 ${(1-count/text.length)*100}% 0 0)`}}/></span>
}
export function Wave(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let frame=0;const a=new Uint8Array(512);const draw=()=>{const c=ref.current!,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);if(audio.analyser)audio.analyser.getByteTimeDomainData(a);else a.fill(128);ctx.strokeStyle='#323232';ctx.lineWidth=1.3;ctx.beginPath();for(let i=0;i<a.length;i++){const x=i/a.length*c.width,y=c.height/2+(a[i]-128)*3.2;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();frame=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(frame)},[]);return <canvas ref={ref} className="wave" width={420} height={230} aria-label="Live audio output waveform"/>}
export function Background({scene,category}:{scene:Scene;category:number}){
 const ref=useRef<HTMLCanvasElement>(null),state=useRef({scene,category});state.current={scene,category};
 useEffect(()=>{let frame=0;const images=shapeIds.map(id=>{const i=new Image();i.src=`/assets/shapes/${id}_symbol_v01.svg`;return i});const canvas=ref.current!,ctx=canvas.getContext('2d')!;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let previous=scene,lastSwitch=performance.now(),old=scene,lastCategory=category;const seed=(i:number)=>{const r=Math.sin(i*12.13)*42342;return r-Math.floor(r)};
  const draw=(now:number)=>{const {scene:s,category:cat}=state.current;if(s!==previous){old=previous;previous=s;lastSwitch=now}if(lastCategory!==cat){lastCategory=cat;lastSwitch=now}const w=innerWidth,h=innerHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.clearRect(0,0,w,h);const visible=['intro','narrative','categories'].includes(s);const age=(now-lastSwitch)/900;const fade=visible?smooth(age):1-smooth(age);const par=reduced?0:Math.sin(now*.00012)*22;const spots=[[.02,.12,440,0],[.7,.04,270,3],[.15,.77,340,1],[.91,.89,330,4]];
   spots.forEach(([x,y,size,k],idx)=>{const selected=s==='categories'?cat:k;const img=images[selected];if(!img.complete)return;const px=x*w+par,py=y*h+Math.cos(now*.00016+idx)*12;const sz=size*h/800;ctx.save();ctx.globalAlpha=.13*fade;ctx.filter='blur(7px)';ctx.translate(px,py);ctx.rotate(idx*.35);ctx.drawImage(img,-sz/2,-sz/2,sz,sz);ctx.restore();if(age<1&&!reduced){ctx.fillStyle='#afa396';ctx.globalAlpha=(1-age)*.22;for(let j=0;j<130;j++){const tx=px+(seed(j+idx*30)-.5)*sz,ty=py+(seed(j+9)-.5)*sz;const isExit=!visible||old!==s;const t=isExit?age:1-age;ctx.fillRect(tx+(seed(j+7)-.5)*w*t,ty+(seed(j+16)-.5)*h*t,1.2,1.2)}}
    if(s==='intro'&&!reduced){const mx=(runtime.pointer.x+1)*w/2,my=(1-runtime.pointer.y)*h/2;if(Math.hypot(mx-px,my-py)<sz*.6){ctx.save();ctx.globalCompositeOperation='destination-out';const gradient=ctx.createRadialGradient(mx,my,0,mx,my,75);gradient.addColorStop(0,'#000');gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.fillRect(mx-75,my-75,150,150);ctx.restore();ctx.globalAlpha=.3;ctx.fillStyle='#9c9386';for(let j=0;j<70;j++){const a=seed(j)*Math.PI*2,r=25+seed(j+11)*65;ctx.fillRect(mx+Math.cos(a+now*.0001)*r,my+Math.sin(a)*r,1,1)}}}
   });ctx.globalAlpha=1;frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[]);
 return <><div className="ambient-light"/><canvas className="background-shapes" ref={ref} aria-hidden="true"/></>
}
