import * as T from 'three';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {materials,asset,type Material} from './data/materials';
import {runtime,clamp,smooth} from './state';

const vertex=`varying vec2 vUv;uniform float deform;uniform vec2 contact;uniform vec2 drag;uniform float kind;uniform float time;void main(){vUv=uv;vec3 p=position;float r=distance(uv,contact);float w=exp(-r*r*18.);if(kind<.5){p.xy+=normalize(p.xy+vec2(.001))*deform*.06*step(.25,fract(uv.x*7.))*w;p.z+=deform*.06*w;}else if(kind<1.5){p.z-=deform*.13*w;p.y*=1.-deform*.10;}else if(kind<2.5){p.z+=deform*sin(uv.y*5.+drag.y)*.2;p.x+=deform*sin(uv.y*4.)*.09;}else if(kind<3.5){p.x+=deform*sin(uv.y*28.)*.05;p.y+=deform*drag.y*.1*w;}else if(kind<4.5){p.x+=deform*drag.x*.15*w;p.z+=deform*sin(uv.y*6.)*.14;}else if(kind<5.5){p.xy=mix(p.xy,contact-.5,deform*w*.6);p.z+=deform*w*.14;}else if(kind<6.5){p.xy+=deform*drag*.12*w;p.z+=deform*sin(r*30.-time*4.)*.07*exp(-r*3.);}else{p.z-=deform*.12*w;p.y*=1.-deform*.08;}gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`;
const fragment=`varying vec2 vUv;uniform sampler2D front;uniform sampler2D micro;uniform float blend;uniform float opacity;uniform float solid;uniform float rearBlur;uniform vec2 hover;uniform float dissolve;void main(){vec4 c=texture2D(front,vUv);if(rearBlur>0.){vec2 b=vec2(rearBlur);c=(c*4.+texture2D(front,vUv+vec2(b.x,0.))+texture2D(front,vUv-vec2(b.x,0.))+texture2D(front,vUv+vec2(0.,b.y))+texture2D(front,vUv-vec2(0.,b.y)))/8.;}if(c.a<.1)discard;float noise=fract(sin(dot(floor(vUv*180.),vec2(12.98,78.23)))*43758.5);if(noise<dissolve)discard;vec3 m=texture2D(micro,(vUv-.5)*1.6+.5).rgb;gl_FragColor=vec4(mix(c.rgb,m,blend)+vec3(solid*.08),c.a*opacity);
#include <colorspace_fragment>
}`;
type Item={data:Material;group:T.Group;photo:T.Mesh<T.PlaneGeometry,T.ShaderMaterial>;model:T.Group;points:T.Points;particles:Float32Array;meshes:T.Mesh[];bases:Float32Array[];size:number;opacity:number;image?:ImageData;arrivalDelay:number};
const rand=(i:number)=>{const v=Math.sin(i*127.1+311.7)*43758.5453;return v-Math.floor(v)};
function modelFor(m:Material,texture:T.Texture,micro:T.Texture){
 const group=new T.Group();const meshes:T.Mesh[]=[];
 const material=new T.MeshStandardMaterial({map:texture,color:m.color,roughness:m.kind==='membrane'?.3:.88,metalness:m.kind==='iron'?.75:0,side:T.DoubleSide,transparent:true});
 const add=(g:T.BufferGeometry,x=0,y=0,z=0)=>{const mat=material.clone();mat.userData.microBlend={value:0};mat.onBeforeCompile=shader=>{shader.uniforms.microBlend=mat.userData.microBlend;shader.uniforms.microMap={value:micro};shader.fragmentShader='uniform float microBlend;uniform sampler2D microMap;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb=mix(diffuseColor.rgb,texture2D(microMap,vMapUv).rgb,microBlend);')};const mesh=new T.Mesh(g,mat);mesh.position.set(x,y,z);group.add(mesh);meshes.push(mesh);return mesh};
 if(m.kind==='plate'||m.kind==='foam'){add(new RoundedBoxGeometry(.86,.62,m.kind==='foam'?.2:.09,5,.035));}
 else if(m.kind==='cushion'){add(new RoundedBoxGeometry(.23,.8,.2,4,.04),-.25);add(new RoundedBoxGeometry(.68,.23,.2,4,.04),0,-.3);add(new RoundedBoxGeometry(.14,.35,.2,4,.035),.31,-.22);}
 else if(m.kind==='iron'){
  const geo=new T.BufferGeometry();const ps:number[]=[];const colors:number[]=[];
  for(let i=0;i<14000;i++){const x=(rand(i*3)-.5)*.94,z=(rand(i*3+1)-.5)*.48;const h=Math.max(0,.52-Math.abs(x+.03)*1.1)*Math.pow(rand(i*3+2),.5);ps.push(x,-.32+h,z);const c=.2+rand(i+7)*.55;colors.push(c,c,c)}
  geo.setAttribute('position',new T.Float32BufferAttribute(ps,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));group.add(new T.Points(geo,new T.PointsMaterial({size:.005,vertexColors:true,transparent:true})));add(new T.CylinderGeometry(.47,.47,.01,50),0,-.33).scale.z=.5;
 }else if(m.kind==='fiber'){
  for(let i=0;i<80;i++){const y=(rand(i)-.5)*.25,z=(rand(i+99)-.5)*.1;const curve=new T.CatmullRomCurve3(Array.from({length:9},(_,j)=>new T.Vector3((j/8-.5)*.94,y+Math.sin(j*.7+i)*.04+Math.sin(j*.55)*.1,z+Math.sin(j+i)*.03)));add(new T.TubeGeometry(curve,20,.002+rand(i+3)*.002,3,false));}
 }else{
  const g=new T.PlaneGeometry(m.kind==='membrane'?.72:.45,.91,36,50);const p=g.attributes.position;
  for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,m.kind==='membrane'?Math.sin(x*10+y*8)*.065:Math.sin(y*6.5)*.14);if(m.kind==='paper')p.setX(i,x+Math.sin(y*5)*.16)}g.computeVertexNormals();add(g);
 }
 return {group,meshes};
}
export class MaterialScene {
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(35,1,1,6000);items:Item[]=[];ray=new T.Raycaster();width=1280;height=800;frame=0;last=0;hoverId:string|null=null;hoverUv=new T.Vector2(-9,-9);reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;onProject?:(p:{id:string;x:number;y:number;depth:number}[])=>void;onReady?:()=>void;
 constructor(public canvas:HTMLCanvasElement){
  this.renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(1);this.renderer.outputColorSpace=T.SRGBColorSpace;this.scene.add(new T.AmbientLight(0xffffff,2));const light=new T.DirectionalLight(0xffeed8,3);light.position.set(-3,5,8);this.scene.add(light);const back=new T.DirectionalLight(0xdce6ff,1.2);back.position.set(3,-1,-5);this.scene.add(back);
  const loader=new T.TextureLoader();const manager=new T.LoadingManager();const texLoader=new T.TextureLoader(manager);manager.onLoad=()=>{runtime.loaded=true;this.onReady?.()};
  materials.forEach((m,index)=>{
   const texture=texLoader.load(asset(m.id,'cutout_front'),tex=>{const c=document.createElement('canvas');c.width=c.height=128;c.getContext('2d')!.drawImage(tex.image,0,0,128,128);this.items[index].image=c.getContext('2d')!.getImageData(0,0,128,128)});texture.colorSpace=T.SRGBColorSpace;const micro=texLoader.load(asset(m.id,'micro_concept'));micro.colorSpace=T.SRGBColorSpace;
   const mat=new T.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{front:{value:texture},micro:{value:micro},blend:{value:0},opacity:{value:0},deform:{value:0},solid:{value:0},rearBlur:{value:0},contact:{value:new T.Vector2(.5,.5)},drag:{value:new T.Vector2()},kind:{value:index},time:{value:0},hover:{value:new T.Vector2(-9,-9)},dissolve:{value:0}}});
   const photo=new T.Mesh(new T.PlaneGeometry(1,1,55,55),mat);const base=loader.load(`/assets/materials/${m.id}/${m.id}_basecolor_v01.jpg`);base.colorSpace=T.SRGBColorSpace;const model=modelFor(m,base,micro);const group=new T.Group();group.add(model.group,photo);photo.position.z=.13;this.scene.add(group);
   const ps=new Float32Array(1800*3);for(let j=0;j<1800;j++){ps[j*3]=rand(j*4+index)-.5;ps[j*3+1]=rand(j*4+index+1)-.5;ps[j*3+2]=0}
   const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(ps.slice(),3));pg.setAttribute('uv',new T.Float32BufferAttribute(Array.from({length:1800},(_,j)=>[ps[j*3]+.5,ps[j*3+1]+.5]).flat(),2));const points=new T.Points(pg,new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{front:{value:texture},opacity:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);gl_PointSize=1.8;}',fragmentShader:'varying vec2 vUv;uniform sampler2D front;uniform float opacity;void main(){vec4 c=texture2D(front,vUv);if(c.a<.4)discard;gl_FragColor=vec4(c.rgb,c.a*opacity);\n#include <colorspace_fragment>\n}'}));group.add(points);
   this.items.push({data:m,group,photo,model:model.group,points,particles:ps,meshes:model.meshes,bases:model.meshes.map(x=>(x.geometry.attributes.position.array as Float32Array).slice()),size:m.size,opacity:0,arrivalDelay:Math.random()*.4});
  });this.resize();this.frame=requestAnimationFrame(this.animate);window.addEventListener('resize',this.resize);
 }
 resize=()=>{this.width=innerWidth;this.height=innerHeight;this.renderer.setSize(this.width,this.height);this.camera.aspect=this.width/this.height;this.camera.position.set(0,0,400/Math.tan(T.MathUtils.degToRad(17.5)));this.camera.updateProjectionMatrix()};
 hit(x:number,y:number){this.ray.setFromCamera(new T.Vector2(x/this.width*2-1,-y/this.height*2+1),this.camera);const hits=this.ray.intersectObjects(this.items.filter(i=>i.opacity>.3).map(i=>i.group),true);for(const h of hits){const item=this.items.find(i=>h.object===i.photo||i.model.children.includes(h.object))!;if(!item)continue;if(h.object===item.photo){if(item.photo.material.uniforms.opacity.value<.25||!h.uv)continue;const uv=h.uv;const a=item.image?.data[(clamp(Math.floor((1-uv.y)*128),0,127)*128+clamp(Math.floor(uv.x*128),0,127))*4+3];if(a!==undefined&&a<50)continue;return {id:item.data.id,uv:uv.clone()}}if(item.model.visible)return {id:item.data.id,uv:h.uv?.clone()||new T.Vector2(.5,.5)}}return null}
 animate=(now:number)=>{
  if(now-this.last<32){this.frame=requestAnimationFrame(this.animate);return}const dt=Math.min(.5,(now-this.last)/1000||.016);this.last=now;const v=runtime.view;const elapsed=(now-runtime.materialTransition)/1000;const arrivalElapsed=(now-runtime.arrivalStarted)/1000;const active=['arrival','explorer','detail','favorites'].includes(v.scene);const idle=!this.reduced&&now-runtime.lastInput>3000&&!runtime.gesture&&!runtime.favMoving;const cameraQ=new T.Quaternion().fromArray(v.camera);const projections:{id:string;x:number;y:number;depth:number}[]=[];
  runtime.deformation=T.MathUtils.damp(runtime.deformation,runtime.gesture&&v.mode==='deform'&&now>runtime.solidUntil?1:0,7,dt);
  this.items.forEach((item,index)=>{
   const m=item.data;let target=new T.Vector3(...m.pos);let size:number=m.size;let opacity=active?1:0;let angle:number=m.angle;let rotation=new T.Quaternion();let modelBlend=0;let micro=0;
   if(v.scene==='explorer'||v.scene==='arrival'){target.applyQuaternion(cameraQ);rotation.copy(cameraQ);modelBlend=smooth(cameraQ.angleTo(new T.Quaternion())/.75);if(arrivalElapsed<2&& !this.reduced){const t=clamp((arrivalElapsed-item.arrivalDelay)/1.2,0,1);const rest=1-smooth(t);target.y+=(m.kind==='iron'?-900:900)*rest;angle+=Math.sin(t*Math.PI*3)*rest*(m.kind==='plate'?.5:.2);size*=1+Math.sin(t*Math.PI*4)*rest*(m.kind==='foam'?.18:.05)}}
   if(v.scene==='detail'){
    if(v.id===m.id){target.set(-80,0,170);size=740*(v.zoom/100)**.68;rotation.fromArray(v.rotation);modelBlend=smooth(rotation.angleTo(new T.Quaternion())/.65);angle=m.kind==='plate'?-.43:0;micro=smooth((v.zoom-180)/60)}else{target.multiplyScalar(3.5);opacity=0}
   }
   if(v.scene==='favorites'){
    const n=v.order.length;const slot=v.order.indexOf(m.id);if(slot<0){opacity=0;target.multiplyScalar(2)}else{const theta=(slot-v.phase)*Math.PI*2/Math.max(n,1);const front=(Math.cos(theta)+1)/2;target.set(Math.sin(theta)*410,20+Math.sin(theta)*32,-160+front*380);size=215+front*325;angle=m.kind==='plate'?-.18:m.angle*.4;opacity=.3+front*.7;if(n===1){target.set(-40,30,160);size=535;opacity=1}item.photo.material.uniforms.dissolve.value=0;}}
   if(v.scene==='detail'&&v.id===m.id&&elapsed<.9&&!this.reduced)angle+=(1-smooth(elapsed/.9))*.7;
   item.opacity=T.MathUtils.damp(item.opacity,opacity,5.5,dt);const f=1-Math.exp(-dt*5.5);item.group.position.lerp(target,f);item.size=T.MathUtils.damp(item.size,size,5.5,dt);item.group.scale.setScalar(item.size);const axis=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),angle);rotation.multiply(axis);item.group.quaternion.slerp(rotation,f);
   // Idle oscillation is an offset that decays smoothly when any input arrives.
   const bobTarget=idle?Math.sin(now*.0008+index)*6:0;item.group.userData.bob=T.MathUtils.damp(item.group.userData.bob||0,bobTarget,4,dt);item.group.position.y+=item.group.userData.bob*dt*3;
   const u=item.photo.material.uniforms;u.opacity.value=item.opacity*(1-modelBlend);u.blend.value=micro;u.rearBlur.value=v.scene==='favorites'?Math.max(0,1-opacity)*.009:0;u.deform.value=v.id===m.id?runtime.deformation:0;u.solid.value=T.MathUtils.damp(u.solid.value,v.id===m.id&&now<runtime.solidUntil?1:0,10,dt);u.drag.value.copy(runtime.drag);u.contact.value.copy(runtime.contact);u.time.value=now*.001;u.hover.value.set(-9,-9);
   if(['arrival','explorer'].includes(v.scene)&&arrivalElapsed<3&&!this.reduced){const t=Math.max(0,arrivalElapsed-item.arrivalDelay);const frequencies=[13,8,5,19,6,11,4,10],strength=[.23,.85,.7,.6,.65,.7,.8,.5];u.deform.value=Math.sin(t*frequencies[index])*Math.exp(-t*2.2)*strength[index];u.drag.value.set(.2,.25);}

   item.model.visible=modelBlend>.005;item.model.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points){const mat=o.material as T.MeshStandardMaterial;mat.opacity=item.opacity*modelBlend;if(mat instanceof T.MeshStandardMaterial){mat.color.set('white');if(mat.userData.microBlend)mat.userData.microBlend.value=micro;}}});
   if(item.model.visible){item.meshes.forEach((mesh,k)=>{const pos=mesh.geometry.attributes.position;const base=item.bases[k];const d=v.id===m.id?runtime.deformation:0;for(let j=0;j<pos.count;j++){let x=base[j*3],y=base[j*3+1],z=base[j*3+2];const r=Math.hypot(x-runtime.contact.x+.5,y-runtime.contact.y+.5);const w=Math.exp(-r*r*12);if(m.kind==='foam'||m.kind==='cushion'){y*=1-d*.16;z-=d*.15*w}else if(m.kind==='paper'){z+=Math.sin(y*7+d)*d*.25;x+=Math.sin(y*5)*d*.16}else if(m.kind==='fiber'){x+=Math.sin(y*20+k)*d*.06;y+=runtime.drag.y*d*.1}else if(m.kind==='plate'){x+=Math.sign(x)*d*.04*w;z+=d*.05*w}else{z+=Math.sin(y*8+now*.002)*d*.13;x+=runtime.drag.x*d*w*.1}pos.setXYZ(j,x,y,z)}pos.needsUpdate=true;mesh.geometry.computeVertexNormals()});
    if(m.kind==='iron'){const pts=item.model.children.find(o=>o instanceof T.Points) as T.Points;const pos=pts.geometry.attributes.position;for(let j=0;j<pos.count;j++){let x=(rand(j*3)-.5)*.94,z=(rand(j*3+1)-.5)*.48;const cx=runtime.contact.x-.5;const h=Math.max(0,.52-Math.abs(x+.03)*1.1)*Math.pow(rand(j*3+2),.5);const d=runtime.deformation;x+=(cx-x)*d*.6;pos.setXYZ(j,x,-.32+h+d*.12,z)}pos.needsUpdate=true}
   }
   const assembly=active&&!runtime.returning?smooth((elapsed-item.arrivalDelay)/.8):1;u.opacity.value*=assembly;
   const powder=v.scene==='detail'&&v.id===m.id&&['plate','cushion'].includes(m.kind)?runtime.deformation:0;const amount=active?Math.max(1-assembly,powder*.65):0;(item.points.material as T.ShaderMaterial).uniforms.opacity.value=item.opacity*amount*.7;item.points.visible=amount>.01;
   if(amount>.01){const a=item.points.geometry.attributes.position;for(let j=0;j<a.count;j++){const x=item.particles[j*3],y=item.particles[j*3+1];const local=1;a.setXYZ(j,x+(rand(j+9)-.5)*amount*local*1.4,y+(rand(j+42)-.5)*amount*local*1.4,(rand(j+3)-.5)*amount*.4)}a.needsUpdate=true}
   item.group.visible=item.opacity>.005;const p=item.group.position.clone().project(this.camera);projections.push({id:m.id,x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2,depth:p.z});
  });this.renderer.render(this.scene,this.camera);this.onProject?.(projections);this.frame=requestAnimationFrame(this.animate);
 };
 dispose(){cancelAnimationFrame(this.frame);window.removeEventListener('resize',this.resize);this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points){o.geometry.dispose();(o.material as T.Material).dispose()}});this.renderer.dispose()}
}

